### ISSUE TITLE
 如何加入团队

### ISSUE THREAD

**Issue by creepebucket** [xiaotianMC/xiaotianMC.github.io#27]
注意到关于我们的页面实际上并没有内容, 我应该如何加入你们?

**Comment by xiaotianMC** [comment]
很抱歉现在才看到，平时不怎么看Github这边，在B站官方账号练习我们会更好。你可以先加入我们的QQ群：109149113

**Comment by xiaotianMC** [comment]
很抱歉现在才看到(っ °Д °;)っ，平时不怎么看Github这边，在B站官方账号联系我们会更好。你可以先加入我们的QQ群：109149113
